sudo: false
language: node_js
node_js:
  - "node"
cache: 
  yarn: true
notifications:
  email:
    on_success: never 
    on_failure: never 
install: false
script:
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - if [ $TRAVIS_TAG =~ ^v?\d+\.\d+\.\d+$ ]; echo $TRAVIS_TAG; fi
  - if [ "$TRAVIS_TAG" =~ ^v?\d+\.\d+\.\d+$ ]; echo $TRAVIS_TAG; fi
  - if [ "$TRAVIS_TAG" =~ "^v?\d+\.\d+\.\d+$" ]; echo $TRAVIS_TAG; fi