version: '2'
services:
  node:
    env_file: 
      - .env
    build: 
      context: ..
      dockerfile: docker/node.dockerfile
  nginx:
    build: 
      context: ..
      dockerfile: docker/nginx.dockerfile
    ports:
     - "80:80"
  mongo:
    image: "mongo"
#docker-compose -p docker up --build